### ISSUE TITLE
客户端连接服务器端测试，最终只能建立32562连接

### ISSUE THREAD

**Issue by huangmeng4520** [emqx/emqx-docs-cn#59]
1. 服务器端和客户端都按照官网配置

![image](https://user-images.githubusercontent.com/8178576/43702172-747b9fca-998b-11e8-9fd8-483ec1b38457.png)

2. 客户端
![image](https://user-images.githubusercontent.com/8178576/43702183-83bd09ec-998b-11e8-8a02-2c027e7a5b1e.png)
请教下，这种情况是我的客户端测试机哪里不对吗?

`[root@lp emqtt_benchmark]# erl
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:16:16] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.2  (abort with ^G)
1> `

**Comment by emqplus** [comment]
Invalid issue. Closed
